spring:
  config:
    import:
      - application-db.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: dev
security:
  jwt:
    secret-key: vingvingdolagoneunvingvingdolagoneunvingvingdolagoneunvingvingdolagoneun
