spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  config:
    import:
      - application-db.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: dev
security:
  jwt:
    secret-key: vingvingdolagoneunvingvingdolagoneunvingvingdolagoneunvingvingdolagoneun
